"""Build the tick probe: a test-only mod that times the game.

Question it answers (Damien, 2026-10-07): do our three mods slow the
simulation down? A stopwatch on the in-game date is too noisy, and
-debug_mode slows the game by itself, so the game times itself instead: the
probe writes one debug.log line at the start of every in-game month, and
every debug.log line carries the real clock ([hh:mm:ss]). Real seconds per
in-game month then come out of tools/tick_report.py.

The line carries no dynamic text on purpose: nothing in it can fail to
resolve (CLAUDE.md, two function tables), and the count of lines is all the
report needs. on_monthly_pulse is the only global pulse the game has (no
weekly one; reference/beta_1.14.5/script_docs/on_actions.log).

Never shipped: it is written straight into the game's mod folder, like the
notification census (tools/build_census_mod.py), with its own mod id.

Usage:  python tools/build_tick_probe.py           (writes the mod)
        python tools/build_tick_probe.py --remove  (deletes it again)
"""
import json
import shutil
import sys
from pathlib import Path

OUT = Path.home() / "Documents" / "Paradox Interactive" / "Victoria 3" / "mod" / "tick_probe"
MOD_ID = "tick_probe"
TAG = "TICK_PROBE"

ON_ACTIONS = f"""﻿# GENERATED by tools/build_tick_probe.py. Test-only, never shipped.
# One debug.log line per in-game month; tools/tick_report.py reads the
# real-time stamps the game puts on each line.
on_monthly_pulse = {{
\ton_actions = {{
\t\ttick_probe_month
\t}}
}}

tick_probe_month = {{
\teffect = {{
\t\tdebug_log = "{TAG}|month"
\t}}
}}
"""


def build():
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / ".metadata").mkdir(parents=True)
    (OUT / "common" / "on_actions").mkdir(parents=True)
    meta = {
        "name": "Tick Probe (test only)",
        "id": MOD_ID,
        "version": "0.01",
        "supported_game_version": "1.13.*",
        "short_description": "Logs one line per in-game month so tools/tick_report.py can time the simulation.",
        "tags": ["Utilities"],
        "relationships": [],
        "game_custom_data": {"multiplayer_synchronized": False},
    }
    # metadata.json must NOT carry a BOM (engine-notes § JSON files must not have a BOM).
    (OUT / ".metadata" / "metadata.json").write_text(json.dumps(meta, indent="\t") + "\n", encoding="utf-8")
    # Every script file MUST carry one (CLAUDE.md § 3); the leading ﻿ above.
    (OUT / "common" / "on_actions" / "zz_tick_probe.txt").write_text(ON_ACTIONS, encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    if "--remove" in sys.argv:
        shutil.rmtree(OUT, ignore_errors=True)
        print(f"removed {OUT}")
    else:
        build()
