"""Build smart_trade/gui/00_smart_trade.gui from a readable template.

The GUI has no variables, so every number is one nested expression, often
300+ characters (a first-week price after the transfer is ~10 levels deep).
Writing those by hand is how typos survive. Here each formula is defined
once by name (@@NAME@@ tokens) and expanded into the template.

Usage:  python tools/gen_smart_trade_gui.py           (writes the file)
        python tools/gen_smart_trade_gui.py --check   (exit 1 if stale)
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "smart_trade" / "gui" / "00_smart_trade.gui"


def mul(a, b): return f"Multiply_CFixedPoint({a}, {b})"
def div(a, b): return f"Divide_CFixedPoint({a}, {b})"
def sub(a, b): return f"Subtract_CFixedPoint({a}, {b})"
def add(a, b): return f"Add_CFixedPoint({a}, {b})"
def fx(v): return f"'(CFixedPoint){v}'"
def gt0(a): return f"GreaterThan_CFixedPoint({a}, {fx(0)})"
def clamp1(a): return f"Max_CFixedPoint(Min_CFixedPoint({a}, {fx(1)}), {fx(-1)})"


# --- Signed treaty, per article (context: Article) -------------------------
A_Q = "Article.GetQuantity"
A_GH = "Article.GetGoods.WithMarketContext(Article.GetSourceCountry.GetMarket.Self)"
A_GP = "Article.GetGoods.WithMarketContext(Article.GetTargetCountry.GetMarket.Self)"
A_PH = f"{A_GH}.GetMarketPrice"
A_PP = f"{A_GP}.GetMarketPrice"
MMP = "GetGoods('merchant_marine').WithMarketContext(GetPlayer.GetMarket.Self).GetMarketPrice"
A_SALE = mul(A_Q, A_PP)
A_BUY = mul(A_Q, A_PH)
A_MARGIN = mul(A_Q, sub(A_PP, A_PH))
A_LANE_MM = "Article.GetShippingLane.GetMerchantMarineDemandRaw"
A_UNITS = "Article.MakeScope.ScriptValue('st_article_lane_units')"
T_UNITS = "Article.GetTreaty.MakeScope.ScriptValue('st_treaty_lane_units')"
A_SHIP = mul(div(A_UNITS, T_UNITS), mul(A_LANE_MM, MMP))
A_NET_LANE = sub(A_MARGIN, A_SHIP)
A_NET_LAND = A_MARGIN
A_HAS_LANE = gt0("Article.MakeScope.ScriptValue('st_article_has_lane')")
A_DIST = div(A_LANE_MM, T_UNITS)

# --- Signed treaty, totals (context: Treaty) -------------------------------
T_MARGIN = "Treaty.MakeScope.ScriptValue('st_treaty_margin')"
T_MONEY = "Treaty.MakeScope.ScriptValue('st_treaty_money')"
T_SHIP = mul("Treaty.GetShippingLaneOf(GetPlayer.Self).GetMerchantMarineDemandRaw", MMP)
T_HAS_LANE = gt0("Treaty.MakeScope.ScriptValue('st_treaty_has_lane')")
T_TRADE_LANE = sub(T_MARGIN, T_SHIP)
T_NET_LANE = add(T_TRADE_LANE, T_MONEY)
T_NET_LAND = add(T_MARGIN, T_MONEY)
T_ANY = f"Or(GreaterThan_CFixedPoint(Abs_CFixedPoint({T_MARGIN}), {fx(0)}), GreaterThan_CFixedPoint(Abs_CFixedPoint({T_MONEY}), {fx(0)}))"

# --- Draft, per article (context: ArticleDraft; Country = maintenance payer) -
D_Q = "ArticleDraft.GetQuantity"
D_GH = "ArticleDraft.GetGoods.WithMarketContext(ArticleDraft.GetFirstOrSource.GetMarket.Self)"
D_GP = "ArticleDraft.GetGoods.WithMarketContext(ArticleDraft.GetSecondOrTarget.GetMarket.Self)"
BASE = "ArticleDraft.GetGoods.GetBasePrice"


def f_imb(b, s):
    """Vanilla price rule: base x (1 + 0.75 x clamp((buy - sell) / min(buy, sell))),
    PRICE_RANGE 0.75, BUY_SELL_DIFF_AT_MAX_FACTOR 2 (00_defines.txt)."""
    return mul(fx(0.75), clamp1(div(sub(b, s), f"Min_CFixedPoint({b}, {s})")))


BH, SH = f"{D_GH}.GetMarketBuyOrders", f"{D_GH}.GetMarketSellOrders"
BP, SP = f"{D_GP}.GetMarketBuyOrders", f"{D_GP}.GetMarketSellOrders"
D_PH = f"{D_GH}.GetMarketPrice"
D_PP = f"{D_GP}.GetMarketPrice"
# First-week price: today's price plus the rule's change from this transfer.
D_PH1 = add(D_PH, mul(BASE, sub(f_imb(add(BH, D_Q), SH), f_imb(BH, SH))))
D_PP1 = add(D_PP, mul(BASE, sub(f_imb(BP, add(SP, D_Q)), f_imb(BP, SP))))
D_RULE_PH = mul(BASE, add(fx(1), f_imb(BH, SH)))
D_RULE_PP = mul(BASE, add(fx(1), f_imb(BP, SP)))
D_MARGIN = mul(D_Q, sub(D_PP1, D_PH1))
D_TQ = "ArticleDraft.GetGoods.GetTradedQuantity"
D_UNITS = div(D_Q, D_TQ)
D_SHIP_LO = mul(D_UNITS, MMP)
D_SHIP_HI = mul(D_SHIP_LO, fx(1.5))
D_NET_LO = sub(D_MARGIN, D_SHIP_HI)
D_NET_HI = sub(D_MARGIN, D_SHIP_LO)
D_BREAKEVEN = div(mul(sub(D_PP1, D_PH1), D_TQ), MMP)
D_ADJ = ("GetScriptedGui('st_markets_adjacent_sgui').IsValid(GuiScope.SetRoot("
         "ArticleDraft.GetFirstOrSource.MakeScope).AddScope('st_other', "
         "ArticleDraft.GetSecondOrTarget.MakeScope).End)")
D_SHOW = "And(ArticleDraft.HasType('goods_transfer'), Country.IsLocalPlayer)"

TOKENS = {k: v for k, v in globals().items() if k.isupper() and isinstance(v, str)}

TEMPLATE = r'''# GENERATED by tools/gen_smart_trade_gui.py. Edit the generator, not this file.
#
# Smart Trade v1, EXPLORATION BUILD (run 3, 2026-10-03). Lines tagged "dev"
# exist only to check our numbers against vanilla's; strip before release.
#
# Redefines three small vanilla types from our own file (no vanilla file is
# copied). THE FILENAME IS LOAD-BEARING: `00_` sorts before treaty_panel.gui
# and treaty_draft_panel.gui, and the engine keeps the first definition it
# reads (docs/engine-notes.md, "A partial .gui override works";
# check_type_overrides_sort_first enforces it).
#   goods_transfer_article        vanilla gui/treaty_panel.gui:1213
#   total_influence_cost          vanilla gui/treaty_panel.gui:756
#   article_draft_influence_cost  vanilla gui/treaty_draft_panel.gui:884
#
# Read-only: no effect is called anywhere. Numbers: the SENDING treasury buys
# at its own market price, sells at the partner's, and pays the lane's
# merchant marine at its own market price (docs/smart-trade-investigation.md).

types smart_trade_types {
	type smart_trade_article_tooltip = RegularTooltip {
		blockoverride "tooltip_content" {
			flowcontainer = {
				direction = vertical
				minimumsize = { 460 -1 }

				custom_tooltip_textbox = { raw_text = "#header [Article.GetGoods.GetName], [Article.GetQuantity|0] a week to [Article.GetTargetCountry.GetNameNoFormatting]#!" }

				# Goods the partner sends: the partner's treasury buys and ships them.
				custom_tooltip_textbox = {
					visible = "[Not(Article.GetSourceCountry.IsLocalPlayer)]"
					raw_text = "[Article.GetSourceCountry.GetNameNoFormatting]'s treasury buys and ships these. Yours pays and earns nothing; your market gets the supply."
				}

				flowcontainer = {
					direction = vertical
					visible = "[Article.GetSourceCountry.IsLocalPlayer]"

					custom_tooltip_textbox = { raw_text = "Sale in [Article.GetTargetCountry.GetNameNoFormatting]'s market: [Article.GetQuantity|0] x @money![@@A_PP@@|2] = @money![@@A_SALE@@|D+=]" }
					custom_tooltip_textbox = { raw_text = "Purchase in your market: [Article.GetQuantity|0] x @money![@@A_PH@@|2] = @money![Negate_CFixedPoint(@@A_BUY@@)|D+=]" }
					custom_tooltip_textbox = {
						visible = "[@@A_HAS_LANE@@]"
						raw_text = "Shipping, lane [Article.GetShippingLane.GetBeginState.GetName] to [Article.GetShippingLane.GetEndState.GetName] (distance x[@@A_DIST@@|2]): @money![Negate_CFixedPoint(@@A_SHIP@@)|D+=]"
					}
					custom_tooltip_textbox = {
						visible = "[Not(@@A_HAS_LANE@@)]"
						raw_text = "Shipping: none, the markets border each other"
					}
					custom_tooltip_textbox = {
						visible = "[@@A_HAS_LANE@@]"
						raw_text = "#bold Net: @money![@@A_NET_LANE@@|D+=] a week#!, @money![Divide_CFixedPoint(@@A_NET_LANE@@, @@A_Q@@)|2+=] per unit"
					}
					custom_tooltip_textbox = {
						visible = "[Not(@@A_HAS_LANE@@)]"
						raw_text = "#bold Net: @money![@@A_NET_LAND@@|D+=] a week#!, @money![Divide_CFixedPoint(@@A_NET_LAND@@, @@A_Q@@)|2+=] per unit"
					}
					custom_tooltip_textbox = { raw_text = "Renegotiating a unit away changes your balance by the opposite of the per-unit figure." }
				}

				tooltip_divider = {}
				custom_tooltip_textbox = { raw_text = "dev X1 script home/partner price=[Article.MakeScope.ScriptValue('st_article_home_price')|2] / [Article.MakeScope.ScriptValue('st_article_partner_price')|2] (GUI [@@A_PH@@|2] / [@@A_PP@@|2])" }
				custom_tooltip_textbox = { raw_text = "dev X1b home price via pricier only=[Article.MakeScope.ScriptValue('st_article_home_price_a')|2], via cheaper only=[Article.MakeScope.ScriptValue('st_article_home_price_b')|2]" }
				custom_tooltip_textbox = { raw_text = "dev X2 script margin=[Article.MakeScope.ScriptValue('st_article_margin')|2] (GUI [@@A_MARGIN@@|2])" }
				custom_tooltip_textbox = { raw_text = "dev X3 units=[@@A_UNITS@@|2] treatyUnits=[@@T_UNITS@@|2] laneMM=[@@A_LANE_MM@@|2] hasLane=[Article.MakeScope.ScriptValue('st_article_has_lane')|0] tq=[Article.MakeScope.ScriptValue('st_article_traded_quantity')|0] (GUI tq [Article.GetGoods.GetTradedQuantity|0])" }
				custom_tooltip_textbox = { raw_text = "dev X4 treaty margin=[Article.GetTreaty.MakeScope.ScriptValue('st_treaty_margin')|2] money=[Article.GetTreaty.MakeScope.ScriptValue('st_treaty_money')|2] hasLane=[Article.GetTreaty.MakeScope.ScriptValue('st_treaty_has_lane')|0]" }
				custom_tooltip_textbox = { raw_text = "dev X5 player margin=[GetPlayer.MakeScope.ScriptValue('st_player_treaty_margin')|2] money=[GetPlayer.MakeScope.ScriptValue('st_player_treaty_money')|2] units=[GetPlayer.MakeScope.ScriptValue('st_player_lane_units')|2] MMprice script=[GetPlayer.MakeScope.ScriptValue('st_player_mm_price')|2] GUI=[@@MMP@@|2] netEst=[GetPlayer.MakeScope.ScriptValue('st_player_treaty_net_est')|2]" }
				custom_tooltip_textbox = { raw_text = "dev X6 vanilla treaties income-expense=[Subtract_CFixedPoint(GetPlayer.PredictTreatyIncome, GetPlayer.PredictTreatyExpenses)|2] (= player margin + money if scripts are right)" }
			}
		}
	}

	type smart_trade_treaty_tooltip = RegularTooltip {
		blockoverride "tooltip_content" {
			flowcontainer = {
				direction = vertical
				minimumsize = { 420 -1 }

				custom_tooltip_textbox = { raw_text = "#header Smart Trade: what [Treaty.GetNameNoFormatting] does to your treasury#!" }
				custom_tooltip_textbox = { raw_text = "Goods you send, sale minus purchase: @money![@@T_MARGIN@@|D+=]" }
				custom_tooltip_textbox = {
					visible = "[@@T_HAS_LANE@@]"
					raw_text = "Shipping lane: @money![Negate_CFixedPoint(@@T_SHIP@@)|D+=]"
				}
				custom_tooltip_textbox = { raw_text = "Money transfers: @money![@@T_MONEY@@|D+=]" }
				custom_tooltip_textbox = {
					visible = "[@@T_HAS_LANE@@]"
					raw_text = "#bold Net: @money![@@T_NET_LANE@@|D+=] a week#!"
				}
				custom_tooltip_textbox = {
					visible = "[Not(@@T_HAS_LANE@@)]"
					raw_text = "#bold Net: @money![@@T_NET_LAND@@|D+=] a week#!"
				}
				custom_tooltip_textbox = { raw_text = "Hover each goods transfer for its own breakdown." }
			}
		}
	}

	type smart_trade_draft_tooltip = RegularTooltip {
		blockoverride "tooltip_content" {
			flowcontainer = {
				direction = vertical
				minimumsize = { 480 -1 }

				custom_tooltip_textbox = { raw_text = "#header Smart Trade prediction: [ArticleDraft.GetGoods.GetName], [ArticleDraft.GetQuantity|0] a week to [ArticleDraft.GetSecondOrTarget.GetNameNoFormatting]#!" }
				custom_tooltip_textbox = { raw_text = "Sale in [ArticleDraft.GetSecondOrTarget.GetNameNoFormatting]'s market: @money![@@D_PP1@@|2] a unit after your supply arrives (now @money![@@D_PP@@|2])" }
				custom_tooltip_textbox = { raw_text = "Purchase in your market: @money![@@D_PH1@@|2] a unit after your buying (now @money![@@D_PH@@|2])" }
				custom_tooltip_textbox = { raw_text = "Sale minus purchase: @money![@@D_MARGIN@@|D+=] a week" }
				custom_tooltip_textbox = {
					visible = "[@@D_ADJ@@]"
					raw_text = "Shipping: none, the markets border each other. #bold Net: @money![@@D_MARGIN@@|D+=] a week#!"
				}
				flowcontainer = {
					direction = vertical
					visible = "[Not(@@D_ADJ@@)]"
					custom_tooltip_textbox = { raw_text = "Shipping by sea: [@@D_UNITS@@|1] merchant marine x @money![@@MMP@@|2] = @money![@@D_SHIP_LO@@|D] on a short route, @money![@@D_SHIP_HI@@|D] on a long one. The route is only known once signed." }
					custom_tooltip_textbox = { raw_text = "#bold Net: @money![@@D_NET_LO@@|D+=] to @money![@@D_NET_HI@@|D+=] a week#!" }
					custom_tooltip_textbox = { raw_text = "Breaks even up to a route multiplier of x[@@D_BREAKEVEN@@|2] (short routes are x1.00; Lisbon to Persia via Suez is x1.17). Below x1.00 it loses on any sea route." }
				}
				custom_tooltip_textbox = { raw_text = "Not counted: how both markets adjust after the first weeks, and the higher merchant-marine price a new lane causes." }
				custom_tooltip_textbox = { raw_text = "The treaty binds for years. Check before sending." }

				tooltip_divider = {}
				custom_tooltip_textbox = { raw_text = "dev Y1 home buy/sell=[@@BH@@|0]/[@@SH@@|0] rule price=[@@D_RULE_PH@@|2] actual=[@@D_PH@@|2] base=[@@BASE@@|2]" }
				custom_tooltip_textbox = { raw_text = "dev Y2 partner buy/sell=[@@BP@@|0]/[@@SP@@|0] rule price=[@@D_RULE_PP@@|2] actual=[@@D_PP@@|2]" }
				custom_tooltip_textbox = { raw_text = "dev Y3 adjacent=[SelectLocalization(@@D_ADJ@@, 'SMART_TRADE_YES', 'SMART_TRADE_NO')] tq=[@@D_TQ@@|0]" }
			}
		}
	}

	# Treasury tooltip: one row per treaty with a money effect.
	type SmartTradeTreatiesTooltipWidget = TooltipWidgetType {
		blockoverride "tooltip_content_after" {
			flowcontainer = {
				direction = vertical
				datamodel = "[GetPlayer.GetInForceTreaties]"
				item = {
					flowcontainer = {
						direction = vertical
						visible = "[@@T_ANY@@]"
						custom_tooltip_textbox = {
							visible = "[@@T_HAS_LANE@@]"
							raw_text = "[Treaty.GetNameNoFormatting]: trade @money![@@T_TRADE_LANE@@|D+=], money @money![@@T_MONEY@@|D+=]"
						}
						custom_tooltip_textbox = {
							visible = "[Not(@@T_HAS_LANE@@)]"
							raw_text = "[Treaty.GetNameNoFormatting]: trade @money![@@T_MARGIN@@|D+=], money @money![@@T_MONEY@@|D+=]"
						}
					}
				}
			}
		}
	}
}

# Registers the treasury tooltip widget under the name the loc line uses
# (vanilla does the same for its own in gui/cooltip.gui).
SmartTradeTreatiesTooltipWidget = {
	name = "SmartTradeTreatiesTooltip"
}

types treaty_panel_types {
	# Vanilla body unchanged (gui/treaty_panel.gui:1213-1241); added: the net
	# chip for goods the player sends, and the breakdown tooltip.
	type goods_transfer_article = widget {
		visible = "[Article.HasType('goods_transfer')]"
		size = { 145 40 }
		using = tooltip_ne

		tooltipwidget = {
			smart_trade_article_tooltip = {}
		}

		flowcontainer = {
			datacontext = "[Article.GetGoods]"
			parentanchor = vcenter
			spacing = 2

			icon = {
				parentanchor = vcenter
				size = { 30 30 }
				texture = "[Goods.GetTexture]"
			}

			textbox = {
				parentanchor = vcenter
				autoresize = yes
				align = nobaseline
				max_width = 130
				using = elide_fontsize_min
				text = "TREATY_SELECTED_ARTICLE_AMOUNT"

				block "text_format" {
					default_format = "#black"
				}
			}
		}

		textbox = {
			visible = "[And(Article.GetSourceCountry.IsLocalPlayer, @@A_HAS_LANE@@)]"
			parentanchor = top|right
			autoresize = yes
			raw_text = "@money![@@A_NET_LANE@@|D+=]"
		}
		textbox = {
			visible = "[And(Article.GetSourceCountry.IsLocalPlayer, Not(@@A_HAS_LANE@@))]"
			parentanchor = top|right
			autoresize = yes
			raw_text = "@money![@@A_NET_LAND@@|D+=]"
		}
	}

	# Vanilla body unchanged (gui/treaty_panel.gui:756-807); added: the
	# treaty's net to the player, beside the player's influence cost, on the
	# signed-treaty panel only (Treaty context).
	type total_influence_cost = hbox {
		minimumsize = { 64 -1 }
		using = tooltip_ne
		tooltip = "TREATY_TOTAL_INFLUENCE_COST"

		block "expand_before" {}

		hbox = {
			margin = { 0 2 }
			spacing = 2

			block "horizontal_margins" {
				margin_left = 2
				margin_right = 5
			}

			background = {
				using = entry_bg_simple_solid

				block "background_alpha" {
					alpha = 0.4
				}

				block "background_margin" {
					margin_left = 10
				}
			}

			### INFLUENCE ICON
			icon = {
				size = { 25 25 }
				texture = "gfx/interface/icons/topbar/influence_icon.dds"
			}

			### INFLUENCE COST
			textbox = {
				autoresize = yes
				align = nobaseline
				using = elide_fontsize_min
				max_width = 35

				block "text_minimumsize" {}

				block "influence_number" {
					raw_text = "#v [Treaty.GetCost(Country.Self)|0]#!"
				}
			}
		}

		### SMART TRADE: treaty net to the player
		textbox = {
			visible = "[And(And(PdxGuiWidget.HasContext('Treaty'), Country.IsLocalPlayer), @@T_HAS_LANE@@)]"
			autoresize = yes
			align = nobaseline
			margin_left = 6
			raw_text = "@money![@@T_NET_LANE@@|D+=]/wk"
			tooltipwidget = { smart_trade_treaty_tooltip = {} }
		}
		textbox = {
			visible = "[And(And(PdxGuiWidget.HasContext('Treaty'), Country.IsLocalPlayer), Not(@@T_HAS_LANE@@))]"
			autoresize = yes
			align = nobaseline
			margin_left = 6
			raw_text = "@money![@@T_NET_LAND@@|D+=]/wk"
			tooltipwidget = { smart_trade_treaty_tooltip = {} }
		}

		block "expand_after" {
			expand = {}
		}
	}
}

types treaty_draft_panel_types {
	# Vanilla's cell (gui/treaty_draft_panel.gui:884-892) wrapped in a vbox so
	# the predicted net can sit under it. The cell's Country is the article's
	# maintenance payer, which for a goods transfer is the sender.
	type article_draft_influence_cost = vbox {
		layoutpolicy_horizontal = expanding

		article_influence_cost = {
			blockoverride "influence_cost_alpha" {
				alpha = "[TransparentIfZero(ArticleDraft.GetCostFor(Country.Self))]"
			}

			blockoverride "influence_cost_text" {
				raw_text = "#v [ArticleDraft.GetCostFor(Country.Self)|0]#!"
			}
		}

		textbox = {
			visible = "[And(@@D_SHOW@@, @@D_ADJ@@)]"
			autoresize = yes
			align = right|nobaseline
			raw_text = "@money![@@D_MARGIN@@|D+=]/wk"
			tooltipwidget = { smart_trade_draft_tooltip = {} }
		}
		textbox = {
			visible = "[And(@@D_SHOW@@, Not(@@D_ADJ@@))]"
			autoresize = yes
			align = right|nobaseline
			raw_text = "@money![@@D_NET_LO@@|D+=] to [@@D_NET_HI@@|D+=]"
			tooltipwidget = { smart_trade_draft_tooltip = {} }
		}
	}
}
'''


def render() -> str:
    text = TEMPLATE
    # Longest names first so @@A_NET_LANE@@ is never clobbered by a shorter token.
    for name in sorted(TOKENS, key=len, reverse=True):
        text = text.replace(f"@@{name}@@", TOKENS[name])
    assert "@@" not in text, [l for l in text.splitlines() if "@@" in l][:3]
    return "﻿" + text


if __name__ == "__main__":
    want = render()
    if "--check" in sys.argv:
        have = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if have != want:
            print(f"STALE: {OUT.relative_to(REPO)} differs from the generator; rerun it.")
            sys.exit(1)
        print("OK: 00_smart_trade.gui matches the generator.")
        sys.exit(0)
    OUT.write_text(want, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(want.splitlines())} lines)")
