"""Smart Notifications: write the ten non-English localization files from
English plus one JSON of translated prose per language.

    python tools/gen_sn_translations.py           write all ten files
    python tools/gen_sn_translations.py --check   exit 1 if any file is stale
    python tools/gen_sn_translations.py --todo    list English prose keys a
                                                  language JSON does not cover

English (smart_notifications/localization/english/) stays hand-written and is
the source of truth: key order, key set and every value's [...] and $...$
come from it. Each English value is handled one of three ways:

- Prose-free (only [...] calls, $...$ references, #formatting and
  punctuation): copied verbatim. About 40 keys, e.g. a diplomatic action's
  name, which is entirely the engine's own text.
- Per-law "ready to enact" toasts (138 laws x name/desc/tooltip): built from
  the two templates "@law_ready_name" and "@law_ready_desc" in the language
  JSON, with @LAW@ and @LAWGROUP@ standing in for $law_x$ / $lawgroup_y$.
  Tooltips are prose-free and copied.
- Everything else: tools/sn_i18n/<language>.json, keyed like English.

A key English gains is a key every JSON lacks, so the generator refuses to
write until all ten are translated -- and check_translations_match_english
fails until it has been rerun.
"""
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LOC = REPO / "smart_notifications" / "localization"
ENGLISH = LOC / "english" / "smart_notifications_l_english.yml"
I18N = Path(__file__).resolve().parent / "sn_i18n"

LANGS = ["french", "german", "spanish", "braz_por", "polish", "russian",
         "simp_chinese", "japanese", "korean", "turkish"]

LINE = re.compile(r'^(\s*)([A-Za-z0-9_.]+)(:\d*)\s*"(.*)"\s*$')
LAW_READY = re.compile(
    r"^notification_smart_notifications_law_ready_toast_(law_[a-z0-9_]+?)_(name|desc)$")


def english_entries():
    """(key, version suffix, value) in file order."""
    out = []
    for line in ENGLISH.read_text(encoding="utf-8-sig").splitlines():
        m = LINE.match(line)
        if m:
            out.append((m.group(2), m.group(3), m.group(4)))
    return out


def is_prose_free(value: str) -> bool:
    rest = re.sub(r"\[[^\]]*\]", "", value)
    rest = re.sub(r"\$[^$]*\$", "", rest)
    rest = re.sub(r"#[a-z]+ |#!", "", rest)
    rest = rest.replace("\\n", "")
    return re.sub(r"[\s•()!:.,\-]", "", rest) == ""


def prose_keys(entries):
    return [k for k, _, v in entries if not is_prose_free(v) and not LAW_READY.match(k)]


def law_group(value: str) -> str:
    m = re.search(r"\$(lawgroup_[a-z0-9_]+)\$", value)
    if not m:
        raise SystemExit(f"law-ready desc without a $lawgroup_...$: {value!r}")
    return m.group(1)


def render(lang: str, entries, table: dict) -> str:
    lines = ["l_%s:" % lang,
             " # GENERATED by tools/gen_sn_translations.py from the English file",
             " # and tools/sn_i18n/%s.json. Edit those, then rerun it." % lang]
    for key, ver, value in entries:
        m = LAW_READY.match(key)
        if m:
            law, part = m.group(1), m.group(2)
            text = table["@law_ready_" + part].replace("@LAW@", "$%s$" % law)
            if part == "desc":
                text = text.replace("@LAWGROUP@", "$%s$" % law_group(value))
        elif is_prose_free(value):
            text = value
        else:
            text = table[key]
        lines.append(' %s%s "%s"' % (key, ver, text))
    return "﻿" + "\n".join(lines) + "\n"


def load(lang: str) -> dict:
    path = I18N / f"{lang}.json"
    return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else {}


def main(argv):
    entries = english_entries()
    needed = prose_keys(entries) + ["@law_ready_name", "@law_ready_desc"]

    problems = []
    for lang in LANGS:
        table = load(lang)
        missing = [k for k in needed if k not in table]
        extra = [k for k in table if k not in needed]
        if missing:
            problems.append(f"{lang}: {len(missing)} untranslated: {', '.join(missing[:6])}")
        if extra:
            problems.append(f"{lang}: {len(extra)} keys English no longer has "
                            f"as prose: {', '.join(extra[:6])}")
    if "--todo" in argv:
        print("\n".join(problems) or "all ten languages cover every English prose key")
        return 0
    if problems:
        print("\n".join(problems))
        return 1

    stale = []
    for lang in LANGS:
        text = render(lang, entries, load(lang))
        out = LOC / lang / f"smart_notifications_l_{lang}.yml"
        current = out.read_text(encoding="utf-8") if out.is_file() else None
        if current == text:
            continue
        if "--check" in argv:
            stale.append(str(out.relative_to(REPO)))
            continue
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {out.relative_to(REPO)}")
    if stale:
        print("stale (rerun tools/gen_sn_translations.py): " + ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
