"""
Generate common/on_actions/15_smart_notifications_law_flag_clear.txt.

The bug it fixes, found live 2026-09-15 in the user's Portugal run: the
"(SN) Law Ready to Enact" alert kept firing for a law that had already been
enacted. The `smart_notifications_wanted_law_<x>` flag is set and cleared ONLY
by the checkbox in the Politics panel
(common/scripted_guis/smart_notifications_law_notify_sgui.txt). Nothing cleared
it when the law actually passed, so the flag outlived the thing it described.

`on_law_activated` is the right hook. Vanilla's own comment above it:

    # owner = owner country of the Law
    # root = law

-- the same root/owner shape the checkbox GUI already uses, so the dispatch
below mirrors its branches exactly.

Vanilla also notes that on_law_activated fires when a law is activated for ANY
reason, including script setting it directly without an enactment process.
That is the behaviour we want: however the law arrived, the player has it, so
the "I want this" flag is spent.

The law list is read from the existing dispatch files rather than re-derived
from the game, so this file cannot drift from them -- and once it is added to
LAW_TYPE_DISPATCH_FILES in check_references.py, the validator enforces that.

Usage:
    python tools/gen_law_flag_clear.py
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
# Smart Notifications moved out of the repo root into its own folder
# 2026-09-16, so each mod in this repo sits in one. Mod CONTENT resolves from
# here; docs/, reference/ and tools/ stay at the repo root.
SN_ROOT = REPO / "smart_notifications"
SOURCE = SN_ROOT / "common" / "scripted_guis" / "smart_notifications_law_notify_sgui.txt"
OUT = SN_ROOT / "common" / "on_actions" / "15_smart_notifications_law_flag_clear.txt"

HEADER = '''# GENERATED by tools/gen_law_flag_clear.py -- do not hand-edit.
#
# Clears `smart_notifications_wanted_law_<x>` when that law actually becomes
# active, so the "(SN) Law Ready to Enact" alert stops pointing at a law the
# player already has.
#
# THE BUG, found live 2026-09-15 in the user's Portugal run: the alert kept
# listing "No Migration Controls" as ready to enact after it had been enacted.
# The wanted flag was set and cleared ONLY by the checkbox in the Politics
# panel (smart_notifications_law_notify_sgui.txt); nothing cleared it when the
# law passed, so the flag outlived the thing it described and the alert had no
# reason to stop.
#
# Root = law, owner = its country -- vanilla's own comment above
# `on_law_activated` in common/on_actions/00_code_on_actions.txt, which is the
# same root/owner shape the checkbox GUI uses, so these branches mirror its.
#
# Vanilla notes that this fires when a law is activated for ANY reason,
# including script setting it directly without an enactment process. That is
# what we want: however the law arrived, the player has it now and the flag is
# spent.
#
# Acceptance criteria: after enacting a law that was flagged wanted, the
# "(SN) Law Ready to Enact" alert stops listing it, and an SNW_LAW_FLAG line
# names the cleared law.

on_law_activated = {
\ton_actions = {
\t\tsmart_notifications_clear_wanted_law_flag
\t}
}

smart_notifications_clear_wanted_law_flag = {
\teffect = {
'''

BRANCH = '''\t\t{kw} = {{
\t\t\tlimit = {{ THIS.type = law_type:{law} }}
\t\t\tTHIS.owner = {{
\t\t\t\tif = {{
\t\t\t\t\tlimit = {{ has_variable = smart_notifications_wanted_law_{short} }}
\t\t\t\t\tremove_variable = smart_notifications_wanted_law_{short}
\t\t\t\t\tdebug_log = "SNW_LAW_FLAG|cleared|{law}|[TimeKeeper.GetCurrentDate.GetString]"
\t\t\t\t}}
\t\t\t}}
\t\t}}
'''


def main():
    text = SOURCE.read_text(encoding="utf-8-sig")
    # Order matters only for readability; dedupe while preserving first sight.
    laws, seen = [], set()
    for m in re.finditer(r"law_type:(law_[a-z_0-9]+)", text):
        if m.group(1) not in seen:
            seen.add(m.group(1))
            laws.append(m.group(1))
    if not laws:
        sys.exit("no law types found in the source dispatch file")

    body = []
    for i, law in enumerate(laws):
        short = law[len("law_"):]
        # The variable names come from the source file's own spelling, which is
        # `smart_notifications_wanted_law_<law minus its law_ prefix>`.
        want = f"smart_notifications_wanted_law_{short}"
        if want not in text:
            sys.exit(f"{law}: expected variable {want} not present in the source "
                     f"-- the naming convention changed, regenerate deliberately")
        body.append(BRANCH.format(kw="if" if i == 0 else "else_if",
                                  law=law, short=short))

    out = HEADER + "".join(body) + "\t}\n}\n"
    OUT.write_bytes(b"\xef\xbb\xbf" + out.encode("utf-8"))
    assert OUT.read_text(encoding="utf-8-sig") == out, "WRITE LOST"
    print(f"wrote {OUT.relative_to(REPO).as_posix()}  ({len(laws)} law types)")


if __name__ == "__main__":
    main()
