"""
Generate the law enactment cooldown tracker for Smart Notifications:

    common/scripted_triggers/02_smart_notifications_law_cooldown_trigger.txt
    common/on_actions/17_smart_notifications_law_cooldown.txt

The bug it fixes, reported on the Workshop page 2026-09-25: after an enactment
fails, the game greys the law out for LAW_ENACTMENT_COOLDOWN_DAYS (730 in
vanilla's 00_defines.txt), but the "(SN) Law Ready to Enact" alert and toast
still said the law was ready. `can_be_enacted` does not consider that lockout,
and triggers.log lists no trigger that does. The engine keeps the cooldown to
itself, so the mod records it.

The define's own wording: "When an enactment fails, or is manually stopped
after at least one checkpoint, that law can't be tried to be enacted for this
many days". So the on_actions below track, per enactment, whether a checkpoint
was reached and whether it passed, then at on_law_enactment_ended stamp a
730-day variable on the country for the law that just stopped.

Ordering relied on, from vanilla's comments in 00_code_on_actions.txt:
on_law_enactment_pass and on_law_enactment_fail both run while the law is
"still considered being enacted", i.e. before on_law_enactment_ended, and
`currently_enacting_law` still resolves inside on_law_enactment_ended.

The law list is read from the existing dispatch files rather than re-derived
from the game, and both outputs are in LAW_TYPE_DISPATCH_FILES in
check_references.py, so they cannot drift from the other per-law files.

Usage:
    python tools/gen_law_cooldown.py
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SN_ROOT = REPO / "smart_notifications"
SOURCE = SN_ROOT / "common" / "scripted_guis" / "smart_notifications_law_notify_sgui.txt"
OUT_TRIGGER = SN_ROOT / "common" / "scripted_triggers" / "02_smart_notifications_law_cooldown_trigger.txt"
OUT_ON_ACTION = SN_ROOT / "common" / "on_actions" / "17_smart_notifications_law_cooldown.txt"

# vanilla common/defines/00_defines.txt, LAW_ENACTMENT_COOLDOWN_DAYS. Script
# cannot read a define, so a mod that changes it will disagree with this.
COOLDOWN_DAYS = 730

TRIGGER_HEADER = '''# GENERATED by tools/gen_law_cooldown.py -- do not hand-edit.
#
# True while THIS (a law) is inside the engine's post-failure enactment
# cooldown, as recorded by common/on_actions/17_smart_notifications_law_cooldown.txt.
# The variable expires on its own after {days} days, the vanilla
# LAW_ENACTMENT_COOLDOWN_DAYS. Used by smart_notifications_law_ready_to_enact.
#
# Only failures that happen with this version of the mod loaded are known: a
# law that failed before the update is not covered until it fails again.
smart_notifications_law_on_cooldown = {{
\tOR = {{
'''

TRIGGER_LINE = ('\t\tAND = {{ THIS.type = law_type:{law}  THIS.owner = '
                '{{ has_variable = smart_notifications_cooldown_law_{short} }} }}\n')

ON_ACTION_HEADER = '''# GENERATED by tools/gen_law_cooldown.py -- do not hand-edit.
#
# Records the engine's law enactment cooldown, which no script trigger exposes.
# vanilla 00_defines.txt, LAW_ENACTMENT_COOLDOWN_DAYS = {days}: "When an
# enactment fails, or is manually stopped after at least one checkpoint, that
# law can't be tried to be enacted for this many days".
#
# Per enactment, two country variables:
#   smart_notifications_law_checkpoint_reached  set by any checkpoint result or a failure
#   smart_notifications_law_enactment_passed    set when the enactment passes
# At on_law_enactment_ended, a checkpoint reached without a pass means the
# law is now locked out, so smart_notifications_cooldown_law_<x> is set for
# {days} days on the law that just stopped. Both per-enactment variables are
# cleared there and again at the next start.
#
# Root is the owner country for every on_action here (vanilla's comments in
# 00_code_on_actions.txt). Player countries only: nothing reads these
# variables on an AI country.
#
# Acceptance criteria: when a wanted law's enactment fails, an
# SNW_LAW_COOLDOWN|recorded line names it, and neither the
# "(SN) Law Ready to Enact" alert nor its toast mentions that law until the
# game's own lockout ends. A law that passes logs nothing here.

on_law_enactment_started = {{
\ton_actions = {{
\t\tsmart_notifications_law_cooldown_reset
\t}}
}}

on_law_checkpoint_success = {{
\ton_actions = {{
\t\tsmart_notifications_law_cooldown_mark_checkpoint
\t}}
}}

on_law_checkpoint_advance = {{
\ton_actions = {{
\t\tsmart_notifications_law_cooldown_mark_checkpoint
\t}}
}}

on_law_checkpoint_debate = {{
\ton_actions = {{
\t\tsmart_notifications_law_cooldown_mark_checkpoint
\t}}
}}

on_law_checkpoint_stall = {{
\ton_actions = {{
\t\tsmart_notifications_law_cooldown_mark_checkpoint
\t}}
}}

on_law_enactment_fail = {{
\ton_actions = {{
\t\tsmart_notifications_law_cooldown_mark_checkpoint
\t}}
}}

on_law_enactment_pass = {{
\ton_actions = {{
\t\tsmart_notifications_law_cooldown_mark_passed
\t}}
}}

on_law_enactment_ended = {{
\ton_actions = {{
\t\tsmart_notifications_law_cooldown_record
\t}}
}}

smart_notifications_law_cooldown_reset = {{
\teffect = {{
\t\tif = {{
\t\t\tlimit = {{ is_player = yes }}
\t\t\tif = {{
\t\t\t\tlimit = {{ has_variable = smart_notifications_law_checkpoint_reached }}
\t\t\t\tremove_variable = smart_notifications_law_checkpoint_reached
\t\t\t}}
\t\t\tif = {{
\t\t\t\tlimit = {{ has_variable = smart_notifications_law_enactment_passed }}
\t\t\t\tremove_variable = smart_notifications_law_enactment_passed
\t\t\t}}
\t\t}}
\t}}
}}

smart_notifications_law_cooldown_mark_checkpoint = {{
\teffect = {{
\t\tif = {{
\t\t\tlimit = {{ is_player = yes }}
\t\t\tset_variable = smart_notifications_law_checkpoint_reached
\t\t}}
\t}}
}}

smart_notifications_law_cooldown_mark_passed = {{
\teffect = {{
\t\tif = {{
\t\t\tlimit = {{ is_player = yes }}
\t\t\tset_variable = smart_notifications_law_enactment_passed
\t\t}}
\t}}
}}

smart_notifications_law_cooldown_record = {{
\teffect = {{
\t\tif = {{
\t\t\tlimit = {{
\t\t\t\tis_player = yes
\t\t\t\thas_variable = smart_notifications_law_checkpoint_reached
\t\t\t\tNOT = {{ has_variable = smart_notifications_law_enactment_passed }}
\t\t\t}}
\t\t\tcurrently_enacting_law ?= {{
'''

ON_ACTION_BRANCH = '''\t\t\t\t{kw} = {{
\t\t\t\t\tlimit = {{ THIS.type = law_type:{law} }}
\t\t\t\t\tTHIS.owner = {{
\t\t\t\t\t\tset_variable = {{ name = smart_notifications_cooldown_law_{short} value = yes days = {days} }}
\t\t\t\t\t\tdebug_log = "SNW_LAW_COOLDOWN|recorded|{law}|[TimeKeeper.GetCurrentDate.GetString]"
\t\t\t\t\t}}
\t\t\t\t}}
'''

ON_ACTION_FOOTER = '''\t\t\t}
\t\t}
\t\tif = {
\t\t\tlimit = { has_variable = smart_notifications_law_checkpoint_reached }
\t\t\tremove_variable = smart_notifications_law_checkpoint_reached
\t\t}
\t\tif = {
\t\t\tlimit = { has_variable = smart_notifications_law_enactment_passed }
\t\t\tremove_variable = smart_notifications_law_enactment_passed
\t\t}
\t}
}
'''


def write_bom(path: Path, text: str):
    path.write_bytes(b"\xef\xbb\xbf" + text.encode("utf-8"))
    assert path.read_text(encoding="utf-8-sig") == text, f"WRITE LOST: {path}"
    print(f"wrote {path.relative_to(REPO).as_posix()}")


def main():
    text = SOURCE.read_text(encoding="utf-8-sig")
    laws, seen = [], set()
    for m in re.finditer(r"law_type:(law_[a-z_0-9]+)", text):
        if m.group(1) not in seen:
            seen.add(m.group(1))
            laws.append(m.group(1))
    if not laws:
        sys.exit("no law types found in the source dispatch file")

    trigger = TRIGGER_HEADER.format(days=COOLDOWN_DAYS)
    on_action = ON_ACTION_HEADER.format(days=COOLDOWN_DAYS)
    for i, law in enumerate(laws):
        short = law[len("law_"):]
        trigger += TRIGGER_LINE.format(law=law, short=short)
        on_action += ON_ACTION_BRANCH.format(kw="if" if i == 0 else "else_if",
                                             law=law, short=short, days=COOLDOWN_DAYS)
    trigger += "\t}\n}\n"
    on_action += ON_ACTION_FOOTER

    write_bom(OUT_TRIGGER, trigger)
    write_bom(OUT_ON_ACTION, on_action)
    print(f"({len(laws)} law types)")


if __name__ == "__main__":
    main()
