"""Generate Smart Trade's per-good shipping rate table from the installed game.

Vanilla's shipping-lane breakdown reads "N from Q goods (1 per T traded)",
where T is the good's `traded_quantity` in common/goods/00_goods.txt
(default GOODS_DEFAULT_TRADE_QUANTITY). Confirmed in game 2026-10-03: the
Austria lane showed "+29.4 from 147 Dye (1 per 5 traded)".

The GUI can read this per good (Goods.GetTradedQuantity), but script cannot,
and the treaty totals are summed in script. So the table is generated, never
hand-typed, and check_references.check_st_traded_quantity_table_current fails
the build when a game patch changes a value.

Usage:  python tools/gen_smart_trade_values.py           (writes the file)
        python tools/gen_smart_trade_values.py --check   (exit 1 if stale)
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GAME = Path(r"C:\Program Files (x86)\Steam\steamapps\common\Victoria 3\game")
OUT = REPO / "smart_trade" / "common" / "script_values" / "smart_trade_traded_quantity.txt"


def default_trade_quantity() -> int:
    text = (GAME / "common" / "defines" / "00_defines.txt").read_text(encoding="utf-8-sig")
    return int(re.search(r"GOODS_DEFAULT_TRADE_QUANTITY\s*=\s*(\d+)", text).group(1))


def goods_quantities() -> dict[str, int]:
    out = {}
    for path in sorted((GAME / "common" / "goods").glob("*.txt")):
        text = re.sub(r"#[^\n]*", "", path.read_text(encoding="utf-8-sig"))
        for m in re.finditer(r"^(\w+)\s*=\s*\{", text, re.M):
            depth, i = 1, m.end()
            while depth and i < len(text):
                depth += (text[i] == "{") - (text[i] == "}")
                i += 1
            body = text[m.end():i - 1]
            # Decimals matter: ships and porcelain are 3.5, fine art 1.5 (a
            # bare \d+ truncated them to 3 and 1; independent review 2026-10-05).
            q = re.search(r"^\s*traded_quantity\s*=\s*([\d.]+)", body, re.M)
            out[m.group(1)] = float(q.group(1)) if q else None
    return out


def render() -> str:
    default = default_trade_quantity()
    goods = goods_quantities()
    lines = [
        "\ufeff# GENERATED by tools/gen_smart_trade_values.py from the installed game's",
        "# common/goods/*.txt. Do not edit by hand; rerun the generator after a patch.",
        "#",
        "# Root: a treaty article with a goods input. Returns the good's",
        "# traded_quantity: vanilla ships 1 merchant marine per this many units.",
        "",
        "st_article_traded_quantity = {",
        f"\tvalue = {default}",
    ]
    for name, q in sorted(goods.items()):
        if q is not None and q != default:
            lines.append(f"\tif = {{ limit = {{ input_goods = g:{name} }} value = {q:g} }}")
    lines += ["}", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    want = render()
    if "--check" in sys.argv:
        have = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if have != want:
            print(f"STALE: {OUT.relative_to(REPO)} does not match the installed game; rerun the generator.")
            sys.exit(1)
        print("OK: traded_quantity table matches the installed game.")
        sys.exit(0)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(want, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")
